### PR TITLE
Fix path of Windows de-/activate scripts + use PKG_NAME

### PR DESCRIPTION
**Pull request by mbargull**
Essentially the same as
https://github.com/conda-forge/toolchain-feedstock/pull/12
and 
https://github.com/conda-forge/toolchain-feedstock/pull/32

### CODE REVIEW

**Comment by mbargull** [comment]
Since the Windows de-/activate scripts are empty, we don't have to increase the build number.

**Comment by scopatz** [comment]
Thanks for putting this in @mbargull. Looks like this fails on windows.

**Comment by scopatz** [comment]
Sorry! Didn't mean to close

**Comment by mbargull** [comment]
I didn't notice the test before!
@jakirkham: I just noticed you increased the (patch) version number for `toolchain` in https://github.com/conda-forge/toolchain-feedstock/pull/33. Is this also necessary to do here?

**Comment by jakirkham** [comment]
That would be best, yes.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
